# Generated by Django 2.2.4 on 2021-10-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team_history',
            field=models.ManyToManyField(related_name='player_history', to='league_app.Team'),
        ),
    ]
